### PR TITLE
Update RGL version to v0.19.0

### PR DESCRIPTION
**Pull request by alek-kam-robotec-ai**
This pull request updates the used RGL version to v0.19.0.

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
It would be an added value if gem versions were somewhat meaningful.

**Comment by alek-kam-robotec-ai** [comment]
@jhanca-robotecai This is an update of the used RGL library version, not the gem itself.

**Comment by jhanca-robotecai** [comment]
> @jhanca-robotecai This is an update of the used RGL library version, not of the gem itself.

Doesn't it mean the gem will be different/better thanks to using a different RGL library under the hood? O3DE uses major.minor.patch versioning. I believe bumping patch in this case is the right thing to do.

**Review by msz-rai — APPROVED** [review]
LGTM!
It works well :+1:

**Review by jhanca-robotecai — APPROVED** [review]
Good job.

Works correctly with ROS 2 Jazzy (Ubuntu 24.04) and ROS 2 Humble (Ubuntu 22.04) with O3DE 2409 and o3de-extras rosi/2409

For the future release: does not build with o3de-extras 2409.x due to changes in Lidar interface (segmentation)

**Pull request merged**
